<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="LAPTOP-1GC1R3HG" failures="1" tests="2" name="Default test" time="0.119" errors="0" timestamp="2024-11-05T11:15:19 MEZ">
  <testcase classname="exceptionsTesting.TestAufgabe3" name="testAufgabe3_1" time="0.021"/>
  <testcase classname="exceptionsTesting.TestAufgabe3" name="testAufgabe3_2" time="0.002">
    <failure type="exceptionsTesting.InvalidNumberException" message="Needs to be a number!">
      <![CDATA[exceptionsTesting.InvalidNumberException: Needs to be a number!
at exceptionsTesting.Aufgabe3.parseInt(Aufgabe3.java:9)
at exceptionsTesting.TestAufgabe3.testAufgabe3_2(TestAufgabe3.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testAufgabe3_2 -->
=======
<testsuite ignored="1" hostname="LAPTOP-TN72FNPT" failures="0" tests="1" name="Default test" time="0.051" errors="0" timestamp="2024-11-05T11:43:24 MEZ">
  <testcase classname="exceptionsTesting.Test_Aufgabe4" name="testReadFile2" time="0.01"/>
  <testcase classname="exceptionsTesting.Test_Aufgabe4" name="testReadFile" time="0.0">
    <ignored/>
  </testcase> <!-- testReadFile -->
>>>>>>> branch 'master' of https://github.com/StringManu/4haSWP.git
</testsuite> <!-- Default test -->
